pipeline {
  agent none
  stages {
    stage('clone repo to custom location') {
      steps {
        dir('/mnt/ansible-playbook-project') {
          sh 'rm -rf *'
          checkout scm
        }
      }
    }
    stage('run dev deployment') {
      steps {
        dir('/mnt/ansible-playbook-project/project') {
          sh 'ansible-playbook master.yaml'
        }
      }
    }
  }
}
