pipeline {
  agent none
  stages {
    stage('clone repo to custom location') {
       agent {
       label 'built-in'
     }
      steps {
        dir('/mnt/ansible-playbook-qa') {
          sh 'rm -rf *'
          checkout scm
        }
      }
    }
    stage('run qa deployment') {
       agent {
       label 'built-in'
     }
      steps {
        dir('/mnt/ansible-playbook-qa/project-qa') {
          sh 'ansible-playbook master.yaml'
        }
      }
    }
  }
}
