pipeline {
  agent none
  stages {
    stage('clone git repo to cutom location') {
      agent {
        label 'built-in'
      }
      steps {
        dir('/mnt/shutdownfile') {
          sh 'rm -rf *'
          checkout scm
        }
      }
    }
    stage('shutdown system on dev') {
      agent {
        label 'dev'
      }
    steps {
      sh 'sudo docker kill tomcat10'
      sh 'sudo docker system prune -a -f'
    }
    }
    stage('shutdown system on qa') {
      agent {
        label 'qa'
      }
    steps {
      sh 'sudo docker kill tomcat10'
      sh 'sudo docker system prune -a -f'
    }
    }
  }
}
